---
title: "Statistical Concepts"
---
#1question
random_vars <- readRDS("random_vars.rds")

view(random_vars)

expected_value <- colMeans(random_vars)
variance <- apply(random_vars, 2, var)
standard_deviation <- sqrt(variance)


cat("Expected Value:\n", expected_value, "\n")
cat("Variance:\n", variance, "\n")
cat("Standard Deviation:\n", standard_deviation, "\n")


#2question
It make sense beacause standard deviation gives us the distribution of data that 
how disperse or spreaded the data is.


#3question

cov <- cov(random_vars)
cor <- cor(random_vars)

cat("Covariance Matrix:\n", cov, "\n")
cat("Correlation Matrix:\n", cor, "\n")


here the correlation represents that its in high in magnitute so which indicates stronger linear relationship between age and income and covarince indicates the measure of linear dependancy of age and income

#4question
Correlation is a standardized measure that ranges from -1 to 1, it makes easier to compare the strength  and direction of the relationship between variables.


#5question

conditional_mean_age_18 <- mean(random_vars$income[random_vars$age <= 18])
conditional_mean_age_18_65 <- mean(random_vars$income[random_vars$age > 18 & random_vars$age < 65])
conditional_mean_age_65 <- mean(random_vars$income[random_vars$age >= 65])


cat("Conditional Expected Value (Age <= 18): ", conditional_mean_age_18, "\n")
cat("Conditional Expected Value (18 < Age < 65): ", conditional_mean_age_18_65, "\n")
cat("Conditional Expected Value (Age >= 65): ", conditional_mean_age_65, "\n")

