---
title: "Randomized Controlled Trials"
---

::: callout-note
You can delete everything in here and start fresh.
:::

library(tidyverse)
library(broom)
library(ggplot2)


abtest_data <- readRDS("abtest_online.rds")


str(abtest_data)



ggplot(abtest_data, aes(x = chatbot, y = previous_visits)) +
  geom_boxplot() +
  labs(title = "Balance Check: Covariates Across Groups", x = "Chatbot", y = "Previous Visits")


reg_model <- lm(purchase_amount ~ chatbot + mobile_device + previous_visits, data = abtest_data)


summary(reg_model)



reg_interaction_model <- lm(purchase_amount ~ chatbot * mobile_device + previous_visits, data = abtest_data)


summary(reg_interaction_model)


ggplot(abtest_data, aes(x = chatbot, y = purchase_amount, color = mobile_device)) +
  geom_boxplot() +
  labs(title = "Interaction Effect: Chatbot and Purchase Amount for Mobile Users", x = "Chatbot", y = "Purchase Amount")


logistic_model <- glm(purchase ~ chatbot + mobile_device + previous_visits, family = binomial(link = 'logit'), data = abtest_data)


summary(logistic_model)
