---
title: "Matching and Subclassification"
---

::: callout-note
You can delete everything in here and start fresh.
:::


data <- readRDS("membership.rds")




dag <- dagitty("dag {
  age -> avg_purch
  sex -> avg_purch
  pre_avg_purch -> avg_purch
  card -> avg_purch
}")


plot(dag)


naive_ate <- mean(data$avg_purch[data$card == 1]) - mean(data$avg_purch[data$card == 0])


exact_match <- matchit(card ~ age + sex + pre_avg_purch, data = data, method = "cem")


nn_match <- matchit(card ~ age + sex + pre_avg_purch, data = data, method = "nearest")


ipw_model <- twang(treatment = data$card, 
                   x = cbind(data$age, data$sex, data$pre_avg_purch),
                   y = data$avg_purch)


exact_match_ate <- lm(avg_purch ~ card, data = match.data(exact_match))


nn_match_ate <- lm(avg_purch ~ card, data = match.data(nn_match))


ipw_ate <- lm(avg_purch ~ card, weights = ipw_model$weights, data = data)


cat("Naive ATE:", naive_ate)
cat("Coarsened Exact Matching ATE:", coef(exact_match_ate)[2])
cat("Nearest-Neighbor Matching ATE:", coef(nn_match_ate)[2])
cat("Inverse Probability Weighting ATE:", coef(ipw_ate)[2])