{
  "hash": "06cf2e12a0bb8b6f909088df29cef8af",
  "result": {
    "markdown": "::: {.cell hash='09_iv_cache/html/unnamed-chunk-1_122c42903d21cb1cfd626918ad9cc426'}\n\n```{.r .cell-code}\nlibrary(dagitty)\n\ndag <- dagitty('\n  dag {\n    Encouragement -> UseNewFeature\n    Encouragement -> TimeSpent\n    UserActivity -> UseNewFeature\n    UserActivity -> TimeSpent\n    Unobserved -> UseNewFeature\n    Unobserved -> TimeSpent\n  }\n')\n\n\nplot(dag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Plot coordinates for graph not supplied! Generating coordinates, see ?coordinates for how to set your own.\n```\n:::\n\n```{.r .cell-code}\ndata <- readRDS(\"rand_enc.rds\")\n\n\n\nnaive_model <- lm(time_spent ~ used_ftr, data = data)\nnaive_estimate <- coef(naive_model)[\"used_ftr\"]\n\nlibrary(AER)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: lmtest\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: zoo\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attaching package: 'zoo'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> The following objects are masked from 'package:base':\n#> \n#>     as.Date, as.Date.numeric\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: sandwich\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Loading required package: survival\n```\n:::\n\n::: {.cell-output-display}\n![](09_iv_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\niv_model <- ivreg(time_spent ~ used_ftr | rand_enc, data = data)\niv_estimate <- coef(iv_model)[\"used_ftr\"]\n\n\ncat(\"Naive Estimate:\", naive_estimate, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Naive Estimate: 10.82269\n```\n:::\n\n```{.r .cell-code}\ncat(\"IV Estimate:\", iv_estimate, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> IV Estimate: 9.738175\n```\n:::\n:::\n\nby checking correlation between our instrument varible and exposure it will tell us may be considering instrument varioble is not adequet process.\n\nand the estimate for used_ftr is 10.82269 in case of naive estimation and is upward biased as comapre to IV estimate (9.738175)",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}